#!/bin/bash

diskused=$( df -h | grep "/dev/sda1" | awk '{print $5}' )

memfree=$( free -mh | grep Mem: | awk '{print $7}' )

connections=$( netstat | grep tcp )

users=$( who | awk '{print $1}' )

echo -e  "Snapshot of current system;
\e[92mDisk used: $diskused
\e[94mFree memory: $memfree
\e[95mLogged in Users: $users
\e[93mOpen Internet Connections: 
$connections 
"

echo "
colar info:
http://misc.flogisoft.com/bash/tip_colors_and_formatting
http://wiki.bash-hackers.org/scripting/style
https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles
"